export type PessoaEnquadramentoTributario =
  | 'LUCRO_REAL_OU_PRESUMIDO'
  | 'SIMPLES_OU_NORMAL_SEM_CREDITO'
  | 'SIMPLES_COM_COBRANCA_ST'
  | 'SIMPLES_SEM_COBRANCA_ST'
  | 'NAO_CONTRIBUINTE'
  | 'MEI_NAO_CONTRIBUINTE'
  | 'MEI_CONTRIBUINTE';
